/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type LessonCompletion = {
  _id: string;
  _type: 'lessonCompletion';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  student?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'student';
  };
  lesson?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'lesson';
  };
  module?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'module';
  };
  course?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'course';
  };
  completedAt?: string;
};

export type Module = {
  _id: string;
  _type: 'module';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  lessons?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'lesson';
  }>;
};

export type Lesson = {
  _id: string;
  _type: 'lesson';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  videoUrl?: string;
  loomUrl?: string;
  notebookUrl?: string;
  notebookFile?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
    };
    media?: unknown;
    _type: 'file';
  };
  colabUrl?: string;
  files?: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
    };
    media?: unknown;
    title?: string;
    description?: string;
    _type: 'file';
    _key: string;
  }>;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?:
          | 'normal'
          | 'h1'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | ({
        _key: string;
      } & Code)
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: 'image';
        _key: string;
      }
  >;
};

export type Enrollment = {
  _id: string;
  _type: 'enrollment';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  student?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'student';
  };
  course?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'course';
  };
  status?: 'pending' | 'active' | 'completed' | 'cancelled';
  amount?: number;
  paymentId?: string;
  enrolledAt?: string;
  expiresAt?: string;
  metadata?: {
    enrollmentSource?: string;
    referralCode?: string;
    campaign?: string;
  };
};

export type Student = {
  _id: string;
  _type: 'student';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  clerkId?: string;
  imageUrl?: string;
  isActive?: boolean;
  createdAt?: string;
  updatedAt?: string;
};

export type Course = {
  _id: string;
  _type: 'course';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  price?: number;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  category?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'category';
  };
  modules?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'module';
  }>;
  instructor?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'instructor';
  };
};

export type Instructor = {
  _id: string;
  _type: 'instructor';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  bio?: string;
  photo?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type Code = {
  _type: 'code';
  code?: string;
  language?:
    | 'javascript'
    | 'typescript'
    | 'python'
    | 'java'
    | 'cpp'
    | 'c'
    | 'csharp'
    | 'php'
    | 'ruby'
    | 'go'
    | 'rust'
    | 'swift'
    | 'kotlin'
    | 'html'
    | 'css'
    | 'sql'
    | 'json'
    | 'yaml'
    | 'markdown'
    | 'shell'
    | 'latex'
    | 'text';
};

export type Category = {
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  icon?: string;
  color?: string;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: 'span';
    _key: string;
  }>;
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
  listItem?: 'bullet' | 'number';
  markDefs?: Array<{
    href?: string;
    _type: 'link';
    _key: string;
  }>;
  level?: number;
  _type: 'block';
  _key: string;
}>;

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | LessonCompletion
  | Module
  | Lesson
  | Enrollment
  | Student
  | Course
  | Instructor
  | Code
  | Category
  | BlockContent
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: src/sanity/lib/courses/getCourseById.ts
// Variable: getCourseByIdQuery
// Query: *[_type == "course" && _id == $id][0] {      ...,  // Spread all course fields      "category": category->{...},  // Expand the category reference, including all its fields      "instructor": instructor->{...},  // Expand the instructor reference, including all its fields      "modules": modules[]-> {  // Expand the array of module references        ...,  // Include all module fields        "lessons": lessons[]-> {...}  // For each module, expand its array of lesson references      }    }
export type GetCourseByIdQueryResult = {
  _id: string;
  _type: 'course';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  price?: number;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  category: {
    _id: string;
    _type: 'category';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
    icon?: string;
    color?: string;
  } | null;
  modules: Array<{
    _id: string;
    _type: 'module';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    lessons: Array<{
      _id: string;
      _type: 'lesson';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      slug?: Slug;
      description?: string;
      videoUrl?: string;
      loomUrl?: string;
      notebookUrl?: string;
      notebookFile?: {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
        };
        media?: unknown;
        _type: 'file';
      };
      colabUrl?: string;
      files?: Array<{
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
        };
        media?: unknown;
        title?: string;
        description?: string;
        _type: 'file';
        _key: string;
      }>;
      content?: Array<
        | ({
            _key: string;
          } & Code)
        | {
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: 'span';
              _key: string;
            }>;
            style?:
              | 'blockquote'
              | 'h1'
              | 'h2'
              | 'h3'
              | 'h4'
              | 'h5'
              | 'h6'
              | 'normal';
            listItem?: 'bullet' | 'number';
            markDefs?: Array<{
              href?: string;
              _type: 'link';
              _key: string;
            }>;
            level?: number;
            _type: 'block';
            _key: string;
          }
        | {
            asset?: {
              _ref: string;
              _type: 'reference';
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            caption?: string;
            _type: 'image';
            _key: string;
          }
      >;
    }> | null;
  }> | null;
  instructor: {
    _id: string;
    _type: 'instructor';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    bio?: string;
    photo?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
  } | null;
} | null;

// Source: src/sanity/lib/courses/getCourseBySlug.ts
// Variable: getCourseBySlugQuery
// Query: *[_type == "course" && slug.current == $slug][0] {      ...,      "category": category->{...},      "instructor": instructor->{...},      "modules": modules[]-> {        ...,        "lessons": lessons[]-> {...}      }    }
export type GetCourseBySlugQueryResult = {
  _id: string;
  _type: 'course';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  price?: number;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  category: {
    _id: string;
    _type: 'category';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
    icon?: string;
    color?: string;
  } | null;
  modules: Array<{
    _id: string;
    _type: 'module';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    lessons: Array<{
      _id: string;
      _type: 'lesson';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      slug?: Slug;
      description?: string;
      videoUrl?: string;
      loomUrl?: string;
      notebookUrl?: string;
      notebookFile?: {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
        };
        media?: unknown;
        _type: 'file';
      };
      colabUrl?: string;
      files?: Array<{
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
        };
        media?: unknown;
        title?: string;
        description?: string;
        _type: 'file';
        _key: string;
      }>;
      content?: Array<
        | ({
            _key: string;
          } & Code)
        | {
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: 'span';
              _key: string;
            }>;
            style?:
              | 'blockquote'
              | 'h1'
              | 'h2'
              | 'h3'
              | 'h4'
              | 'h5'
              | 'h6'
              | 'normal';
            listItem?: 'bullet' | 'number';
            markDefs?: Array<{
              href?: string;
              _type: 'link';
              _key: string;
            }>;
            level?: number;
            _type: 'block';
            _key: string;
          }
        | {
            asset?: {
              _ref: string;
              _type: 'reference';
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            caption?: string;
            _type: 'image';
            _key: string;
          }
      >;
    }> | null;
  }> | null;
  instructor: {
    _id: string;
    _type: 'instructor';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    bio?: string;
    photo?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
  } | null;
} | null;

// Source: src/sanity/lib/courses/getCourseProgress.ts
// Variable: progressQuery
// Query: {    "completedLessons": *[_type == "lessonCompletion" && student._ref == $studentId && course._ref == $courseId] {      ...,      "lesson": lesson->{...},      "module": module->{...}    },    "course": *[_type == "course" && _id == $courseId][0] {      ...,      "modules": modules[]-> {        ...,        "lessons": lessons[]-> {...}      }    }  }
export type ProgressQueryResult = {
  completedLessons: Array<{
    _id: string;
    _type: 'lessonCompletion';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    student?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'student';
    };
    lesson: {
      _id: string;
      _type: 'lesson';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      slug?: Slug;
      description?: string;
      videoUrl?: string;
      loomUrl?: string;
      notebookUrl?: string;
      notebookFile?: {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
        };
        media?: unknown;
        _type: 'file';
      };
      colabUrl?: string;
      files?: Array<{
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
        };
        media?: unknown;
        title?: string;
        description?: string;
        _type: 'file';
        _key: string;
      }>;
      content?: Array<
        | ({
            _key: string;
          } & Code)
        | {
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: 'span';
              _key: string;
            }>;
            style?:
              | 'blockquote'
              | 'h1'
              | 'h2'
              | 'h3'
              | 'h4'
              | 'h5'
              | 'h6'
              | 'normal';
            listItem?: 'bullet' | 'number';
            markDefs?: Array<{
              href?: string;
              _type: 'link';
              _key: string;
            }>;
            level?: number;
            _type: 'block';
            _key: string;
          }
        | {
            asset?: {
              _ref: string;
              _type: 'reference';
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            caption?: string;
            _type: 'image';
            _key: string;
          }
      >;
    } | null;
    module: {
      _id: string;
      _type: 'module';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      lessons?: Array<{
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: 'lesson';
      }>;
    } | null;
    course?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'course';
    };
    completedAt?: string;
  }>;
  course: {
    _id: string;
    _type: 'course';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    price?: number;
    slug?: Slug;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
    category?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'category';
    };
    modules: Array<{
      _id: string;
      _type: 'module';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      lessons: Array<{
        _id: string;
        _type: 'lesson';
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title?: string;
        slug?: Slug;
        description?: string;
        videoUrl?: string;
        loomUrl?: string;
        notebookUrl?: string;
        notebookFile?: {
          asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
          };
          media?: unknown;
          _type: 'file';
        };
        colabUrl?: string;
        files?: Array<{
          asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
          };
          media?: unknown;
          title?: string;
          description?: string;
          _type: 'file';
          _key: string;
        }>;
        content?: Array<
          | ({
              _key: string;
            } & Code)
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: 'span';
                _key: string;
              }>;
              style?:
                | 'blockquote'
                | 'h1'
                | 'h2'
                | 'h3'
                | 'h4'
                | 'h5'
                | 'h6'
                | 'normal';
              listItem?: 'bullet' | 'number';
              markDefs?: Array<{
                href?: string;
                _type: 'link';
                _key: string;
              }>;
              level?: number;
              _type: 'block';
              _key: string;
            }
          | {
              asset?: {
                _ref: string;
                _type: 'reference';
                _weak?: boolean;
                [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
              };
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              alt?: string;
              caption?: string;
              _type: 'image';
              _key: string;
            }
        >;
      }> | null;
    }> | null;
    instructor?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'instructor';
    };
  } | null;
};

// Source: src/sanity/lib/courses/getCourses.ts
// Variable: getCoursesQuery
// Query: *[_type == "course"] {    ...,    "slug": slug.current,    "category": category->{...},    "instructor": instructor->{...},    "modules": modules[]->{      ...,      "lessons": lessons[]->{        ...,        "hasVideo": defined(videoUrl) || defined(loomUrl),        "hasNotebook": defined(notebookUrl) || defined(notebookFile),        "hasColab": defined(colabUrl),        "fileCount": count(files)      }    }  }
export type GetCoursesQueryResult = Array<{
  _id: string;
  _type: 'course';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  price?: number;
  slug: string | null;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  category: {
    _id: string;
    _type: 'category';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
    icon?: string;
    color?: string;
  } | null;
  modules: Array<{
    _id: string;
    _type: 'module';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    lessons: Array<{
      _id: string;
      _type: 'lesson';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      slug?: Slug;
      description?: string;
      videoUrl?: string;
      loomUrl?: string;
      notebookUrl?: string;
      notebookFile?: {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
        };
        media?: unknown;
        _type: 'file';
      };
      colabUrl?: string;
      files?: Array<{
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
        };
        media?: unknown;
        title?: string;
        description?: string;
        _type: 'file';
        _key: string;
      }>;
      content?: Array<
        | ({
            _key: string;
          } & Code)
        | {
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: 'span';
              _key: string;
            }>;
            style?:
              | 'blockquote'
              | 'h1'
              | 'h2'
              | 'h3'
              | 'h4'
              | 'h5'
              | 'h6'
              | 'normal';
            listItem?: 'bullet' | 'number';
            markDefs?: Array<{
              href?: string;
              _type: 'link';
              _key: string;
            }>;
            level?: number;
            _type: 'block';
            _key: string;
          }
        | {
            asset?: {
              _ref: string;
              _type: 'reference';
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            caption?: string;
            _type: 'image';
            _key: string;
          }
      >;
      hasVideo: false | true;
      hasNotebook: false | true;
      hasColab: false | true;
      fileCount: number | null;
    }> | null;
  }> | null;
  instructor: {
    _id: string;
    _type: 'instructor';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    bio?: string;
    photo?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
  } | null;
}>;

// Source: src/sanity/lib/courses/searchCourses.ts
// Variable: searchQuery
// Query: *[_type == "course" && (    title match $term + "*" ||    description match $term + "*" ||    category->name match $term + "*"  )] {    ...,    "slug": slug.current,    "category": category->{...},    "instructor": instructor->{...},    "modules": modules[]->{      ...,      "lessons": lessons[]->{        ...,        "hasVideo": defined(videoUrl) || defined(loomUrl),        "hasNotebook": defined(notebookUrl) || defined(notebookFile),        "hasColab": defined(colabUrl),        "fileCount": count(files)      }    }  }
export type SearchQueryResult = Array<{
  _id: string;
  _type: 'course';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  price?: number;
  slug: string | null;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  category: {
    _id: string;
    _type: 'category';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
    icon?: string;
    color?: string;
  } | null;
  modules: Array<{
    _id: string;
    _type: 'module';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    lessons: Array<{
      _id: string;
      _type: 'lesson';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      slug?: Slug;
      description?: string;
      videoUrl?: string;
      loomUrl?: string;
      notebookUrl?: string;
      notebookFile?: {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
        };
        media?: unknown;
        _type: 'file';
      };
      colabUrl?: string;
      files?: Array<{
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
        };
        media?: unknown;
        title?: string;
        description?: string;
        _type: 'file';
        _key: string;
      }>;
      content?: Array<
        | ({
            _key: string;
          } & Code)
        | {
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: 'span';
              _key: string;
            }>;
            style?:
              | 'blockquote'
              | 'h1'
              | 'h2'
              | 'h3'
              | 'h4'
              | 'h5'
              | 'h6'
              | 'normal';
            listItem?: 'bullet' | 'number';
            markDefs?: Array<{
              href?: string;
              _type: 'link';
              _key: string;
            }>;
            level?: number;
            _type: 'block';
            _key: string;
          }
        | {
            asset?: {
              _ref: string;
              _type: 'reference';
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            caption?: string;
            _type: 'image';
            _key: string;
          }
      >;
      hasVideo: false | true;
      hasNotebook: false | true;
      hasColab: false | true;
      fileCount: number | null;
    }> | null;
  }> | null;
  instructor: {
    _id: string;
    _type: 'instructor';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    bio?: string;
    photo?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
  } | null;
}>;

// Source: src/sanity/lib/enrollment/enrollmentService.ts
// Variable: enrollmentStatusQuery
// Query: *[_type == "student" && clerkId == $clerkId][0] {        _id,        "enrollments": *[_type == "enrollment" && student._ref == ^._id && course._ref == $courseId] {          _id,          status,          enrolledAt,          expiresAt,          amount,          paymentId        }[0]      }
export type EnrollmentStatusQueryResult = {
  _id: string;
  enrollments: {
    _id: string;
    status: 'active' | 'cancelled' | 'completed' | 'pending' | null;
    enrolledAt: string | null;
    expiresAt: string | null;
    amount: number | null;
    paymentId: string | null;
  } | null;
} | null;
// Variable: studentEnrollmentsQuery
// Query: *[_type == "student" && clerkId == $clerkId][0] {        "enrollments": *[_type == "enrollment" && student._ref == ^._id] {          _id,          status,          enrolledAt,          expiresAt,          amount,          paymentId,          "course": course-> {            _id,            title,            slug,            image,            category->{ name }          }        } | order(enrolledAt desc)      }
export type StudentEnrollmentsQueryResult = {
  enrollments: Array<{
    _id: string;
    status: 'active' | 'cancelled' | 'completed' | 'pending' | null;
    enrolledAt: string | null;
    expiresAt: string | null;
    amount: number | null;
    paymentId: string | null;
    course: {
      _id: string;
      title: string | null;
      slug: Slug | null;
      image: {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
      } | null;
      category: {
        name: string | null;
      } | null;
    } | null;
  }>;
} | null;

// Source: src/sanity/lib/lessons/getLessonById.ts
// Variable: getLessonByIdQuery
// Query: *[_type == "lesson" && _id == $id][0] {    ...,    files[]{      _key,      asset->{        _id,        _type,        originalFilename,        url,        mimeType,        size      },      title,      description    },    "module": module->{      ...,      "course": course->{...}    },    notebookUrl,    colabUrl,    notebookFile{      asset->{        url,        originalFilename      }    }  }
export type GetLessonByIdQueryResult = {
  _id: string;
  _type: 'lesson';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  videoUrl?: string;
  loomUrl?: string;
  notebookUrl: string | null;
  notebookFile: {
    asset: {
      url: string | null;
      originalFilename: string | null;
    } | null;
  } | null;
  colabUrl: string | null;
  files: Array<{
    _key: string;
    asset: {
      _id: string;
      _type: 'sanity.fileAsset';
      originalFilename: string | null;
      url: string | null;
      mimeType: string | null;
      size: number | null;
    } | null;
    title: string | null;
    description: string | null;
  }> | null;
  content?: Array<
    | ({
        _key: string;
      } & Code)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?:
          | 'blockquote'
          | 'h1'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'normal';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: 'image';
        _key: string;
      }
  >;
  module: null;
} | null;

// Source: src/sanity/lib/lessons/getLessonCompletionStatus.ts
// Variable: completionStatusQuery
// Query: *[_type == "lessonCompletion" && student._ref == $studentId && lesson._ref == $lessonId][0] {    ...  }
export type CompletionStatusQueryResult = {
  _id: string;
  _type: 'lessonCompletion';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  student?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'student';
  };
  lesson?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'lesson';
  };
  module?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'module';
  };
  course?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'course';
  };
  completedAt?: string;
} | null;

// Source: src/sanity/lib/lessons/getLessonCompletions.ts
// Variable: getCompletionsQuery
// Query: {    "completedLessons": *[_type == "lessonCompletion" && student._ref == $studentId && course._ref == $courseId] {      ...,      "lesson": lesson->{...},      "module": module->{...}    },    "course": *[_type == "course" && _id == $courseId][0] {      ...,      "modules": modules[]-> {        ...,        "lessons": lessons[]-> {...}      }    }  }
export type GetCompletionsQueryResult = {
  completedLessons: Array<{
    _id: string;
    _type: 'lessonCompletion';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    student?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'student';
    };
    lesson: {
      _id: string;
      _type: 'lesson';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      slug?: Slug;
      description?: string;
      videoUrl?: string;
      loomUrl?: string;
      notebookUrl?: string;
      notebookFile?: {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
        };
        media?: unknown;
        _type: 'file';
      };
      colabUrl?: string;
      files?: Array<{
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
        };
        media?: unknown;
        title?: string;
        description?: string;
        _type: 'file';
        _key: string;
      }>;
      content?: Array<
        | ({
            _key: string;
          } & Code)
        | {
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: 'span';
              _key: string;
            }>;
            style?:
              | 'blockquote'
              | 'h1'
              | 'h2'
              | 'h3'
              | 'h4'
              | 'h5'
              | 'h6'
              | 'normal';
            listItem?: 'bullet' | 'number';
            markDefs?: Array<{
              href?: string;
              _type: 'link';
              _key: string;
            }>;
            level?: number;
            _type: 'block';
            _key: string;
          }
        | {
            asset?: {
              _ref: string;
              _type: 'reference';
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            caption?: string;
            _type: 'image';
            _key: string;
          }
      >;
    } | null;
    module: {
      _id: string;
      _type: 'module';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      lessons?: Array<{
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: 'lesson';
      }>;
    } | null;
    course?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'course';
    };
    completedAt?: string;
  }>;
  course: {
    _id: string;
    _type: 'course';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    price?: number;
    slug?: Slug;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
    category?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'category';
    };
    modules: Array<{
      _id: string;
      _type: 'module';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      lessons: Array<{
        _id: string;
        _type: 'lesson';
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title?: string;
        slug?: Slug;
        description?: string;
        videoUrl?: string;
        loomUrl?: string;
        notebookUrl?: string;
        notebookFile?: {
          asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
          };
          media?: unknown;
          _type: 'file';
        };
        colabUrl?: string;
        files?: Array<{
          asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
          };
          media?: unknown;
          title?: string;
          description?: string;
          _type: 'file';
          _key: string;
        }>;
        content?: Array<
          | ({
              _key: string;
            } & Code)
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: 'span';
                _key: string;
              }>;
              style?:
                | 'blockquote'
                | 'h1'
                | 'h2'
                | 'h3'
                | 'h4'
                | 'h5'
                | 'h6'
                | 'normal';
              listItem?: 'bullet' | 'number';
              markDefs?: Array<{
                href?: string;
                _type: 'link';
                _key: string;
              }>;
              level?: number;
              _type: 'block';
              _key: string;
            }
          | {
              asset?: {
                _ref: string;
                _type: 'reference';
                _weak?: boolean;
                [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
              };
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              alt?: string;
              caption?: string;
              _type: 'image';
              _key: string;
            }
        >;
      }> | null;
    }> | null;
    instructor?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'instructor';
    };
  } | null;
};

// Source: src/sanity/lib/student/getEnrolledCourses.ts
// Variable: getEnrolledCoursesQuery
// Query: *[_type == "student" && clerkId == $clerkId][0] {    "enrolledCourses": *[_type == "enrollment" && student._ref == ^._id] {      ...,      "course": course-> {        ...,        "slug": slug.current,        "category": category->{...},        "instructor": instructor->{          ...,          "photo": photo.asset->url        }      }    }  }
export type GetEnrolledCoursesQueryResult = {
  enrolledCourses: Array<{
    _id: string;
    _type: 'enrollment';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    student?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'student';
    };
    course: {
      _id: string;
      _type: 'course';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      price?: number;
      slug: string | null;
      description?: string;
      image?: {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
      };
      category: {
        _id: string;
        _type: 'category';
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        name?: string;
        slug?: Slug;
        description?: string;
        icon?: string;
        color?: string;
      } | null;
      modules?: Array<{
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: 'module';
      }>;
      instructor: {
        _id: string;
        _type: 'instructor';
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        name?: string;
        bio?: string;
        photo: string | null;
      } | null;
    } | null;
    status?: 'active' | 'cancelled' | 'completed' | 'pending';
    amount?: number;
    paymentId?: string;
    enrolledAt?: string;
    expiresAt?: string;
    metadata?: {
      enrollmentSource?: string;
      referralCode?: string;
      campaign?: string;
    };
  }>;
} | null;

// Source: src/sanity/lib/student/getStudentByClerkId.ts
// Variable: getStudentByClerkIdQuery
// Query: *[_type == "student" && clerkId == $clerkId][0]
export type GetStudentByClerkIdQueryResult = {
  _id: string;
  _type: 'student';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  clerkId?: string;
  imageUrl?: string;
  isActive?: boolean;
  createdAt?: string;
  updatedAt?: string;
} | null;

// Source: src/sanity/lib/student/isEnrolledInCourse.ts
// Variable: studentQuery
// Query: *[_type == "student" && clerkId == $clerkId][0] { _id }
export type StudentQueryResult = {
  _id: string;
} | null;
// Variable: enrollmentQuery
// Query: *[_type == "enrollment" && student._ref == $studentId && course._ref == $courseId][0]
export type EnrollmentQueryResult = {
  _id: string;
  _type: 'enrollment';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  student?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'student';
  };
  course?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'course';
  };
  status?: 'active' | 'cancelled' | 'completed' | 'pending';
  amount?: number;
  paymentId?: string;
  enrolledAt?: string;
  expiresAt?: string;
  metadata?: {
    enrollmentSource?: string;
    referralCode?: string;
    campaign?: string;
  };
} | null;

// Source: src/sanity/lib/student/studentService.ts
// Variable: studentByClerkIdQuery
// Query: *[_type == "student" && clerkId == $clerkId][0] {        _id,        clerkId,        email,        firstName,        lastName,        imageUrl,        isActive,        createdAt,        updatedAt      }
export type StudentByClerkIdQueryResult = {
  _id: string;
  clerkId: string | null;
  email: string | null;
  firstName: string | null;
  lastName: string | null;
  imageUrl: string | null;
  isActive: boolean | null;
  createdAt: string | null;
  updatedAt: string | null;
} | null;
// Variable: allStudentsQuery
// Query: *[_type == "student"] | order(createdAt desc) {        _id,        clerkId,        email,        firstName,        lastName,        imageUrl,        isActive,        createdAt,        updatedAt      }
export type AllStudentsQueryResult = Array<{
  _id: string;
  clerkId: string | null;
  email: string | null;
  firstName: string | null;
  lastName: string | null;
  imageUrl: string | null;
  isActive: boolean | null;
  createdAt: string | null;
  updatedAt: string | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "course" && _id == $id][0] {\n      ...,  // Spread all course fields\n      "category": category->{...},  // Expand the category reference, including all its fields\n      "instructor": instructor->{...},  // Expand the instructor reference, including all its fields\n      "modules": modules[]-> {  // Expand the array of module references\n        ...,  // Include all module fields\n        "lessons": lessons[]-> {...}  // For each module, expand its array of lesson references\n      }\n    }': GetCourseByIdQueryResult;
    '*[_type == "course" && slug.current == $slug][0] {\n      ...,\n      "category": category->{...},\n      "instructor": instructor->{...},\n      "modules": modules[]-> {\n        ...,\n        "lessons": lessons[]-> {...}\n      }\n    }': GetCourseBySlugQueryResult;
    '{\n    "completedLessons": *[_type == "lessonCompletion" && student._ref == $studentId && course._ref == $courseId] {\n      ...,\n      "lesson": lesson->{...},\n      "module": module->{...}\n    },\n    "course": *[_type == "course" && _id == $courseId][0] {\n      ...,\n      "modules": modules[]-> {\n        ...,\n        "lessons": lessons[]-> {...}\n      }\n    }\n  }':
      | ProgressQueryResult
      | GetCompletionsQueryResult;
    '*[_type == "course"] {\n    ...,\n    "slug": slug.current,\n    "category": category->{...},\n    "instructor": instructor->{...},\n    "modules": modules[]->{\n      ...,\n      "lessons": lessons[]->{\n        ...,\n        "hasVideo": defined(videoUrl) || defined(loomUrl),\n        "hasNotebook": defined(notebookUrl) || defined(notebookFile),\n        "hasColab": defined(colabUrl),\n        "fileCount": count(files)\n      }\n    }\n  }': GetCoursesQueryResult;
    '*[_type == "course" && (\n    title match $term + "*" ||\n    description match $term + "*" ||\n    category->name match $term + "*"\n  )] {\n    ...,\n    "slug": slug.current,\n    "category": category->{...},\n    "instructor": instructor->{...},\n    "modules": modules[]->{\n      ...,\n      "lessons": lessons[]->{\n        ...,\n        "hasVideo": defined(videoUrl) || defined(loomUrl),\n        "hasNotebook": defined(notebookUrl) || defined(notebookFile),\n        "hasColab": defined(colabUrl),\n        "fileCount": count(files)\n      }\n    }\n  }': SearchQueryResult;
    '\n      *[_type == "student" && clerkId == $clerkId][0] {\n        _id,\n        "enrollments": *[_type == "enrollment" && student._ref == ^._id && course._ref == $courseId] {\n          _id,\n          status,\n          enrolledAt,\n          expiresAt,\n          amount,\n          paymentId\n        }[0]\n      }\n    ': EnrollmentStatusQueryResult;
    '\n      *[_type == "student" && clerkId == $clerkId][0] {\n        "enrollments": *[_type == "enrollment" && student._ref == ^._id] {\n          _id,\n          status,\n          enrolledAt,\n          expiresAt,\n          amount,\n          paymentId,\n          "course": course-> {\n            _id,\n            title,\n            slug,\n            image,\n            category->{ name }\n          }\n        } | order(enrolledAt desc)\n      }\n    ': StudentEnrollmentsQueryResult;
    '*[_type == "lesson" && _id == $id][0] {\n    ...,\n    files[]{\n      _key,\n      asset->{\n        _id,\n        _type,\n        originalFilename,\n        url,\n        mimeType,\n        size\n      },\n      title,\n      description\n    },\n    "module": module->{\n      ...,\n      "course": course->{...}\n    },\n    notebookUrl,\n    colabUrl,\n    notebookFile{\n      asset->{\n        url,\n        originalFilename\n      }\n    }\n  }': GetLessonByIdQueryResult;
    '*[_type == "lessonCompletion" && student._ref == $studentId && lesson._ref == $lessonId][0] {\n    ...\n  }': CompletionStatusQueryResult;
    '*[_type == "student" && clerkId == $clerkId][0] {\n    "enrolledCourses": *[_type == "enrollment" && student._ref == ^._id] {\n      ...,\n      "course": course-> {\n        ...,\n        "slug": slug.current,\n        "category": category->{...},\n        "instructor": instructor->{\n          ...,\n          "photo": photo.asset->url\n        }\n      }\n    }\n  }': GetEnrolledCoursesQueryResult;

    '*[_type == "student" && clerkId == $clerkId][0] { _id }': StudentQueryResult;
    '*[_type == "enrollment" && student._ref == $studentId && course._ref == $courseId][0]': EnrollmentQueryResult;
    '\n      *[_type == "student" && clerkId == $clerkId][0] {\n        _id,\n        clerkId,\n        email,\n        firstName,\n        lastName,\n        imageUrl,\n        isActive,\n        createdAt,\n        updatedAt\n      }\n    ': StudentByClerkIdQueryResult;
    '\n      *[_type == "student"] | order(createdAt desc) {\n        _id,\n        clerkId,\n        email,\n        firstName,\n        lastName,\n        imageUrl,\n        isActive,\n        createdAt,\n        updatedAt\n      }\n    ': AllStudentsQueryResult;
  }
}
